import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import UserLayout from "~/components/user/UserLayout";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Akun Kita</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserLayout>
        <div className=" w-full min-h-screen bg-gray-500">Sliders</div>
        <div className=" min-h-screen container bg-gray-200 mx-auto">
          hello
        </div>
      </UserLayout>
    </>
  );
};

export default Home;
